"""Obsidian vault export."""
from __future__ import annotations
import re
from pathlib import Path
from typing import Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from xme.engine import MemoryEngine


def _slug(title: str) -> str:
    return re.sub(r"[^\w\- ]", "", title).strip().replace(" ", "-").lower()[:60]


async def export_obsidian(
    engine: "MemoryEngine",
    project_id: str,
    output_dir: Optional[str] = None,
) -> Path:
    base = Path(output_dir or f".xanther/obsidian/{project_id}")
    base.mkdir(parents=True, exist_ok=True)
    (base / ".obsidian").mkdir(exist_ok=True)

    # Minimal Obsidian config
    (base / ".obsidian" / "app.json").write_text('{"legacyEditor": false}')

    facts = await engine.facts.list_facts(project_id, limit=1000)
    episodes = await engine.episodic.list_episodes(project_id, limit=500)

    # Write fact notes
    for fact in facts:
        subdir = base / f"{fact.fact_type}s"
        subdir.mkdir(exist_ok=True)
        fname = _slug(fact.title or fact.fact_id)
        content = [
            f"---",
            f"tags: [{fact.fact_type}, xme]",
            f"confidence: {fact.confidence}",
            f"created: {fact.created_at[:10]}",
            f"project: {fact.project_id}",
            f"---",
            "",
            f"# {fact.title}",
            "",
            fact.content,
            "",
        ]
        if fact.metadata:
            content += ["## Metadata", ""]
            for k, v in fact.metadata.items():
                content.append(f"- **{k}**: {v}")
            content.append("")
        if fact.related_fact_ids:
            content += ["## Related", ""]
            for rid in fact.related_fact_ids[:5]:
                content.append(f"- [[{rid}]]")
        (subdir / f"{fname}.md").write_text("\n".join(content))

    # Write episode notes
    ep_dir = base / "sessions"
    ep_dir.mkdir(exist_ok=True)
    for ep in episodes:
        date = ep.started_at[:10]
        fname = f"{date}-{ep.episode_id[:8]}"
        content = [
            f"---",
            f"tags: [session, xme]",
            f"date: {date}",
            f"outcome: {ep.outcome}",
            f"user: {ep.user_id}",
            f"---",
            "",
            f"# Session {date}",
            "",
            f"**User**: {ep.user_id}  ",
            f"**Outcome**: {ep.outcome}  ",
            "",
            "## Summary",
            "",
            ep.summary or "_No summary_",
            "",
        ]
        if ep.fact_ids:
            content += ["## Facts Extracted", ""]
            for fid in ep.fact_ids[:10]:
                content.append(f"- [[{fid}]]")
        (ep_dir / f"{fname}.md").write_text("\n".join(content))

    # Write index
    idx = [f"# {project_id} Memory Index", "", f"Generated by XME.", "",
           "## Facts", ""]
    for ft in ["decision", "attempt", "preference", "convention", "entity"]:
        count = sum(1 for f in facts if f.fact_type == ft)
        if count:
            idx.append(f"- [[{ft}s/]] ({count} {ft}s)")
    idx += ["", "## Sessions", ""]
    for ep in episodes[:20]:
        idx.append(f"- [[sessions/{ep.started_at[:10]}-{ep.episode_id[:8]}]] — {ep.summary[:60]}")
    (base / "index.md").write_text("\n".join(idx))

    return base
