"""Wiki markdown export (agent-navigable)."""
from __future__ import annotations
import re
from pathlib import Path
from typing import Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from xme.engine import MemoryEngine


def _slug(s: str) -> str:
    return re.sub(r"[^\w\-]", "-", s.lower())[:60].strip("-")


async def export_wiki(
    engine: "MemoryEngine",
    project_id: str,
    output_dir: Optional[str] = None,
) -> Path:
    base = Path(output_dir or f".xanther/wiki/{project_id}")
    base.mkdir(parents=True, exist_ok=True)

    facts = await engine.facts.list_facts(project_id, limit=1000)
    episodes = await engine.episodic.list_episodes(project_id, limit=200)
    stats = await engine.stats(project_id)

    # Index
    idx = [
        f"# {project_id} — Knowledge Base",
        "",
        f"> Generated by XME. {stats['total_facts']} facts, "
        f"{stats['total_episodes']} sessions.",
        "",
        "## Decisions",
        "",
    ]
    for f in [x for x in facts if x.fact_type == "decision"]:
        idx.append(f"- [{f.title}](decisions/{_slug(f.title)}.md)")
    idx += ["", "## Sessions", ""]
    for ep in episodes[:30]:
        idx.append(f"- [{ep.started_at[:10]} — {ep.summary[:50]}](sessions/{ep.episode_id[:8]}.md)")

    (base / "index.md").write_text("\n".join(idx))

    # Decisions
    dec_dir = base / "decisions"
    dec_dir.mkdir(exist_ok=True)
    for f in [x for x in facts if x.fact_type == "decision"]:
        body = [f"# {f.title}", "", f.content, "",
                f"*Confidence: {f.confidence} | Created: {f.created_at[:10]}*"]
        (dec_dir / f"{_slug(f.title)}.md").write_text("\n".join(body))

    # Sessions
    ses_dir = base / "sessions"
    ses_dir.mkdir(exist_ok=True)
    for ep in episodes:
        body = [
            f"# Session {ep.started_at[:10]}",
            "", f"**User**: {ep.user_id} | **Outcome**: {ep.outcome}",
            "", "## Summary", "", ep.summary or "_No summary_",
        ]
        (ses_dir / f"{ep.episode_id[:8]}.md").write_text("\n".join(body))

    return base
